/**
 * GENERATED by scripts/import-research.mjs from verified research extracts
 * (JSON with verbatim evidence quotes; research folder BRIEF.md). Do not edit
 * numbers by hand: fix the research JSON and re-run the importer.
 *
 * VERIFIED_SOURCES   every source cited by a verified range or threshold
 * VERIFIED_RANGES    reference-interval candidates by indicator code
 * VERIFIED_THRESHOLDS decision thresholds (categories / targets)
 * RESEARCH_GAPS      what the research could not verify (shown in 指标库)
 */
import type { RangeCandidateInput, Source, ThresholdInput } from "./schema.js";

export const VERIFIED_SOURCES: Source[] = [
  {
    "id": "src_wst404_1_2012",
    "org": "中华人民共和国卫生部 (临床检验标准专业委员会)",
    "title": "临床常用生化检验项目参考区间 第1部分：血清丙氨酸氨基转移酶、天门冬氨酸氨基转移酶、碱性磷酸酶和γ-谷氨酰基转移酶",
    "identifier": "WS/T 404.1—2012",
    "url": "https://hbba.sacinfo.org.cn/attachment/onlineRead/7ff09b68ccd3344ed0e1a09cf35eb634",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-26",
    "status": "现行 (发布 2012-12-25, 实施 2013-08-01; 备案号 38407-2013; 依据 卫通〔2012〕23号)。未发现修订或代替版本。",
    "notes": "全文是扫描图像，我在官方在线阅读页(全国标准信息公共服务平台/行业标准备案平台)逐页 PNG 上目视读表，没有文字层。状态和日期来自 https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F1D4BBBB19E05397BE0A0AB44A。",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_2_2012",
    "org": "中华人民共和国卫生部 (临床检验标准专业委员会)",
    "title": "临床常用生化检验项目参考区间 第2部分：血清总蛋白、白蛋白",
    "identifier": "WS/T 404.2—2012",
    "url": "https://hbba.sacinfo.org.cn/attachment/onlineRead/112298e54c19a9a3e3c7ffefc32d59c6",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-26",
    "status": "现行 (发布 2012-12-25, 实施 2013-08-01; 备案号 38408-2013)。未发现修订或代替版本。",
    "notes": "扫描图像，我目视读表。标准标题只写「总蛋白、白蛋白」，但表1实际还给出球蛋白(GLB)和白蛋白/球蛋白比值(A/G)。状态和日期来自 https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F1E388BB19E05397BE0A0AB44A。",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_4_2018",
    "org": "中华人民共和国国家卫生健康委员会",
    "title": "临床常用生化检验项目参考区间 第4部分：血清总胆红素、直接胆红素",
    "identifier": "WS/T 404.4—2018",
    "url": "https://www.nhc.gov.cn/wjw/s9492/201805/67aa364588f74ec69a1de85f893ed2c4/files/1739781483928_13416.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-26",
    "status": "现行 (发布 2018-04-27, 实施 2018-11-01)。这是本部分的首个版本，前言无「代替」字样。",
    "notes": "国家卫健委官方 PDF，有文字层，我用 pdfjs 提取，未做 OCR。表头单位 μmol/L 中的 μ 字符在文字层丢失，evidence_quote 里按提取原样保留。状态来自 https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F14B2BBB19E05397BE0A0AB44A。",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_5_2015",
    "org": "中华人民共和国国家卫生和计划生育委员会",
    "title": "临床常用生化检验项目参考区间 第5部分：血清尿素、肌酐",
    "identifier": "WS/T 404.5—2015",
    "url": "https://www.nhc.gov.cn/ewebeditor/uploadfile/2015/05/20150504152412571.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-26",
    "status": "现行 (发布 2015-04-21, 实施 2015-10-01)",
    "notes": "用于确认系列结构和日期。第6、7、8部分(2015-04-21 发布, 2015-10-01 实施)的状态来自 samr 页面: 第6部分 id=8B1827F21911BB19E05397BE0A0AB44A, 第7部分 id=8B1827F2267DBB19E05397BE0A0AB44A, 第8部分 id=8B1827F2282BBB19E05397BE0A0AB44A。",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_3_2012",
    "org": "中华人民共和国卫生部（现国家卫生健康委员会）",
    "title": "临床常用生化检验项目参考区间 第3部分：血清钾、钠、氯",
    "identifier": "WS/T 404.3—2012",
    "url": "https://img.antpedia.com/standard/files/pdfs_ora/CN-WS/f8e/WS_T%20404.3-2012_8125.pdf",
    "level": "national_cn",
    "verifiedVia": "secondary",
    "retrieved": "2026-09-26",
    "status": "现行 (2012-12-25 发布, 2013-08-01 实施); std.samr.gov.cn 页面标注现行、无被代替信息; 未检索到修订版",
    "notes": "The PDF is a mirror of the printed China Standards Press edition and is an image scan (CCITT). I converted it to PNG and read table 1 visually. The mirror has only 3 pages: cover, foreword plus references, and a page holding the body (scope, table 1, 5.1) and A.4/A.5. Appendix A.1-A.3 and appendix B are missing, so the age range and the measurement method are not confirmed from the primary text. Publication and implementation dates are read from the cover image. Status page: https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F1B9A9BB19E05397BE0A0AB44A. Official notice 卫通〔2012〕23号 (2012-12-25) lists 404.3 (https://www.waizi.org.cn/law/18715.html).",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_6_2015",
    "org": "中华人民共和国国家卫生和计划生育委员会",
    "title": "临床常用生化检验项目参考区间 第6部分：血清总钙、无机磷、镁、铁",
    "identifier": "WS/T 404.6—2015",
    "url": "https://www.nhc.gov.cn/wjw/s9492/201504/fc914ad5981a49a88213940422ad24e1/files/1739781583780_16290.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-26",
    "status": "现行 (2015-04-21 发布, 2015-10-01 实施); 未发现被代替记录 (WS/T 404.9—2026 前言的系列清单仍列本部分)",
    "notes": "The official NHC PDF has an extractable text layer. The dates are printed on the cover. I did not open a std.samr.gov.cn status page for 404.6 itself (the page I checked for 404.7 shows 现行 with the same 2015 dates). Status is inferred from the 404.9—2026 series list.",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst405_2012",
    "org": "中华人民共和国卫生部 (临床检验标准专业委员会)",
    "title": "血细胞分析参考区间",
    "identifier": "WS/T 405—2012",
    "url": "https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F1CB6DBB19E05397BE0A0AB44A",
    "level": "national_cn",
    "verifiedVia": "secondary",
    "retrieved": "2026-09-26",
    "status": "现行 (发布 2012-12-25, 实施 2013-08-01; 全国标准信息公共服务平台显示状态为现行, 未见被代替/废止信息)",
    "notes": "现行状态/日期来自 std.samr.gov.cn (primary)。表格数值取自全文扫描 PDF 镜像 https://labivd.com/storage/upload/20240219/65d36b1ab6d0e.pdf (9页图片扫描, 无文字层), 由我目视读取表1页面图像, 非文本复制; nhc.gov.cn 页面 (https://www.nhc.gov.cn/wjw/s9492/201301/d893733b674945afa63bc33f3cc7e60d.shtml) 返回 HTTP 412, 未能打开官方 PDF, 故数值为 secondary。原文区间写作 a～b, 按两端含。WS/T 402 已有 2024 版, 但那是参考区间制定方法标准, 并未替代 WS/T 405。",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_nhc_weight_mgmt_2024",
    "org": "国家卫生健康委办公厅",
    "title": "体重管理指导原则（2024年版）",
    "identifier": "国卫办医急函〔2024〕469号",
    "url": "https://www.nhc.gov.cn/ylyjs/zcwj/202412/75cb79c171c94def9e768193e65484f7/files/1736390749000_59785.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "PDF text extracted and read. 文号 and date (2024-12-05) confirmed via the notice reposted at https://wjw.xinjiang.gov.cn/hfpc/wsyj1/202501/c27573430e8249a5a3259f1a1fb389b4.shtml (secondary). Both 附表1 and 附表2 are marked 引自：《成人体重判定》（WS/T 428—2013）.",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_nhc_obesity_2024",
    "org": "国家卫生健康委员会（国家卫生健康委办公厅印发）",
    "title": "肥胖症诊疗指南（2024年版）",
    "identifier": "国卫办医政函〔2024〕382号",
    "url": "https://www.gov.cn/zhengce/zhengceku/202410/P020241020715873679737.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Notice page https://www.gov.cn/zhengce/zhengceku/202410/content_6981734.htm: 国家卫生健康委办公厅关于印发肥胖症诊疗指南（2024年版）的通知, 国卫办医政函〔2024〕382号, 成文日期 2024-10-12. PDF colophon: 国家卫生健康委办公厅 2024 年 10 月 14 日印发. Its ref [30] is WS/T 428-2013. Journal reprint titled 肥胖症中国诊疗指南(2024年版), author 中华人民共和国国家卫生健康委员会医政司, 协和医学杂志, doi 10.12290/xhyxzz.2024-0918 (landing page https://xhyxzz.pumch.cn/article/doi/10.12290/xhyxzz.2024-0918 fetched; volume/issue/pages NOT verified, see unverified).",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cds_dm_2024",
    "org": "中华医学会糖尿病学分会",
    "title": "中国糖尿病防治指南（2024版）",
    "identifier": "doi:10.3760/cma.j.cn115791-20241203-00705",
    "url": "https://files.sciconf.cn/master/50/33230/202501/20250120111901_47273.pdf",
    "level": "cn_guideline",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "PDF (linked from the CDS website) text-extracted; citation and DOI taken verbatim from the PDF's 引用本文 line. Journal landing page: https://rs.yiigle.com/cmaid/1525739 (paywalled). Table cells were extracted as separate lines, so row/column alignment of 表2 is reconstructed from line order (see threshold notes).",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cse_hua_2019",
    "org": "中华医学会内分泌学分会",
    "title": "中国高尿酸血症与痛风诊疗指南(2019)",
    "identifier": "doi:10.3760/cma.j.issn.1000-6699.2020.01.001",
    "url": "https://seleguide.yiigle.com/uploads/guide_html/中国高尿酸血症与痛风诊疗指南(2019).html",
    "level": "cn_guideline",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Full-text HTML on the CMA yiigle guideline platform, read directly. Journal landing page https://rs.yiigle.com/cmaid/1179377 (paywalled). Citation also confirmed on medsci.cn and in 中国全科医学 2021,24(33):4196-4199 reference list.",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cra_gout_2023",
    "org": "中华医学会风湿病学分会（徐东、朱小霞、邹和建等 代表）",
    "title": "痛风诊疗规范",
    "identifier": "doi:10.3760/cma.j.cn112138-20221027-00796",
    "url": "https://99homecare.com/files/2023.pdf",
    "level": "cn_guideline",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Text read from a third-party mirror of the journal PDF (journal header and 引用本文 line present in the file). Official landing page reportedly https://rs.yiigle.com/cmaid/1471591 (not fetched).",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cn_htn_2024",
    "org": "中国高血压防治指南修订委员会;高血压联盟(中国);中国医疗保健国际交流促进会高血压病学分会;中国老年医学学会高血压分会;中国老年保健协会高血压分会;中国卒中学会;中国疾病预防控制中心慢性非传染性疾病预防控制中心",
    "title": "中国高血压防治指南(2024年修订版)",
    "identifier": "doi:10.16439/j.issn.1673-7245.2024.07.002",
    "url": "https://cjournal.hep.com.cn/1673-7245/CN/10.16439/j.issn.1673-7245.2024.07.002",
    "level": "cn_guideline",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Citation, DOI and author list confirmed on the journal landing page. Text read from the journal's own 98-page PDF (https://cjournal.hep.com.cn/1673-7245/CN/PDF/10.16439/j.issn.1673-7245.2024.07.002). This is the current edition and supersedes 2018. It keeps grades 1-3 and 3级, adds a 单纯舒张期高血压 row, adds baPWV>=18 m/s to target-organ damage, and changes cfPWV from >=12 to >=10 m/s. Journal page numbers are inferred: PDF page n = journal p.602+n, because the running-footer digits came out reversed in extraction.",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cn_htn_tod_2025",
    "org": "高血压联盟(中国);中国医疗保健国际交流促进会高血压病学分会;中国医药教育协会临床肾脏病学专业委员会;《高血压患者靶器官动态评估与长程管理专家共识》委员会",
    "title": "高血压患者靶器官动态评估与长程管理专家共识",
    "identifier": "doi:10.16439/j.issn.1673-7245.2025-0346",
    "url": "http://zhgxyzz.xml-journal.net/cn/article/pdf/preview/10.16439/j.issn.1673-7245.2025-0346.pdf",
    "level": "cn_consensus",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Full PDF text read. The page range 1111-1124 comes from the running footers of the article PDF. Corresponding author 王继光.",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cn_elderly_extremity_as_2012",
    "org": "《老年人四肢动脉粥样硬化性疾病诊治中国专家建议2012》写作组;中华医学会老年医学分会;中华医学会外科学分会血管外科专业组;中华老年医学杂志编辑委员会",
    "title": "老年人四肢动脉粥样硬化性疾病诊治中国专家建议(2012)",
    "identifier": "doi:10.3760/cma.j.issn.0254-9026.2013.02.002",
    "url": "https://seleguide.yiigle.com/uploads/guide_html/%E8%80%81%E5%B9%B4%E4%BA%BA%E5%9B%9B%E8%82%A2%E5%8A%A8%E8%84%89%E7%B2%A5%E6%A0%B7%E7%A1%AC%E5%8C%96%E6%80%A7%E7%96%BE%E7%97%85%E8%AF%8A%E6%B2%BB%E4%B8%AD%E5%9B%BD%E4%B8%93%E5%AE%B6%E5%BB%BA%E8%AE%AE(2012).html",
    "level": "cn_consensus",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Full-text HTML on the CMA (yiigle) guideline site. This is an older expert recommendation (专家建议) aimed at the elderly, and it is the only Chinese document found with the 4-tier ABI categories. The ABI criterion cites its reference [21].",
    "scope": [
      "decision_threshold"
    ]
  },
  {
    "id": "src_cn_echo_2016",
    "org": "中华医学会超声医学分会超声心动图学组",
    "title": "中国成年人超声心动图检查测量指南",
    "identifier": "doi:10.3760/cma.j.issn.1004-4477.2016.08.001",
    "url": "https://cmab.yiigle.com/uploads/guide_html/%E4%B8%AD%E5%9B%BD%E6%88%90%E5%B9%B4%E4%BA%BA%E8%B6%85%E5%A3%B0%E5%BF%83%E5%8A%A8%E5%9B%BE%E6%A3%80%E6%9F%A5%E6%B5%8B%E9%87%8F%E6%8C%87%E5%8D%97.html",
    "level": "cn_guideline",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Based on EMINCA (Han Chinese healthy adults 18-79 y; male n=678, female n=716). Read from the publisher's full-text HTML via WebFetch; the PDF could not be text-extracted. Tables give sex- and age-banded 95% ranges; only the sex totals are used here. No FS (fractional shortening) value found in the guideline.",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_7_2015",
    "org": "中华人民共和国国家卫生和计划生育委员会",
    "title": "临床常用生化检验项目参考区间 第7部分:血清乳酸脱氢酶、肌酸激酶",
    "identifier": "WS/T 404.7—2015",
    "url": "https://www.nhc.gov.cn/ewebeditor/uploadfile/2015/05/20150504152437621.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Reference population: Chinese adults aged 20-79. Note 2 says results are traceable to internationally recognised reference methods (附录B).",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_wst404_8_2015",
    "org": "中华人民共和国国家卫生和计划生育委员会",
    "title": "临床常用生化检验项目参考区间 第8部分:血清淀粉酶",
    "identifier": "WS/T 404.8—2015",
    "url": "https://www.nhc.gov.cn/ewebeditor/uploadfile/2015/05/20150504152450722.pdf",
    "level": "national_cn",
    "verifiedVia": "primary",
    "retrieved": "2026-09-24",
    "notes": "Reference population: Chinese adults aged 20-79. Total serum amylase.",
    "scope": [
      "reference_range"
    ]
  },
  {
    "id": "src_cn_lipid_guideline_2023",
    "org": "中国血脂管理指南修订联合专家委员会（通信作者：李建军、赵水平、高润霖）",
    "title": "中国血脂管理指南（2023年）",
    "identifier": "中国循环杂志 2023;38(3):237-271；DOI 10.3969/j.issn.1000-3614.2023.03.001（文章编号 1000-3614(2023)03-0237-35）。同文另刊：中华心血管病杂志 2023;51(3):221-255",
    "url": "https://heart-valve-1311769631.cos.ap-beijing.myqcloud.com/cbcb7d7d7ea39e4f20cb5af01e6653ef9fde94e7.pdf",
    "level": "cn_guideline",
    "verifiedVia": "secondary",
    "retrieved": "2026-09-26",
    "status": "现行（2023年3月发表；替代2016年修订版《中国成人血脂异常防治指南》。未见更新版，也未见被替代的记录）",
    "notes": "PDF全文来自第三方COS镜像，页眉为中国循环杂志2023年3月第38卷第3期。文本层与南方医科大学镜像 aike.smu.edu.cn 一致（两份均为35页）。中华心血管病杂志版官方页面 https://csc.cma.org.cn/art/2023/3/28/art_619_50122.html 可打开，但其PDF附件（filename=96b4e603cee74b7fb208b278aa92bd8b.pdf）我没有抽取文字核对，所以本次没有做到 verified_via=primary。所有数字均由PDF文本层提取，没有对照表格图像；表3各列在文本层中被压平，是按列顺序还原的。",
    "scope": [
      "reference_range",
      "decision_threshold"
    ]
  }
];

export const VERIFIED_RANGES: Record<string, RangeCandidateInput[]> = {
  "ALT": [
    {
      "id": "wst404_1_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 9,
      "high": 50,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第1行 ALT",
      "conditions": "无脚注标记的 ALT 行，即试剂中不含5'-磷酸吡哆醛的检测体系(由脚注a的对照推断，标准未直接写出「不含」)",
      "evidenceQuote": "血清丙氨酸氨基转移酶(ALT)  U/L  男 9～50"
    },
    {
      "id": "wst404_1_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 7,
      "high": 40,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第1行 ALT",
      "conditions": "同上，无脚注标记(不含5'-磷酸吡哆醛)",
      "evidenceQuote": "血清丙氨酸氨基转移酶(ALT)  U/L  女 7～40"
    },
    {
      "id": "wst404_1_2012-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 9,
      "high": 60,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第2行 ALT(带脚注a)",
      "conditions": "脚注a: 试剂中含有5'-磷酸吡哆醛",
      "evidenceQuote": "血清丙氨酸氨基转移酶(ALT)ᵃ  U/L  男 9～60；脚注：ᵃ 试剂中含有5'-磷酸吡哆醛。"
    },
    {
      "id": "wst404_1_2012-4",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 7,
      "high": 45,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第2行 ALT(带脚注a)",
      "conditions": "脚注a: 试剂中含有5'-磷酸吡哆醛",
      "evidenceQuote": "血清丙氨酸氨基转移酶(ALT)ᵃ  U/L  女 7～45；脚注：ᵃ 试剂中含有5'-磷酸吡哆醛。"
    }
  ],
  "AST": [
    {
      "id": "wst404_1_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 15,
      "high": 40,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第3行 AST",
      "conditions": "无脚注标记的 AST 行，即试剂中不含5'-磷酸吡哆醛的检测体系(由脚注a的对照推断)",
      "evidenceQuote": "血清天门冬氨酸氨基转移酶(AST)  U/L  男 15～40"
    },
    {
      "id": "wst404_1_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 13,
      "high": 35,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1 第3行 AST",
      "conditions": "同上，无脚注标记",
      "evidenceQuote": "血清天门冬氨酸氨基转移酶(AST)  U/L  女 13～35"
    },
    {
      "id": "wst404_1_2012-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 15,
      "high": 45,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) 第1行 AST(带脚注a)",
      "conditions": "脚注a: 试剂中含有5'-磷酸吡哆醛",
      "evidenceQuote": "血清天门冬氨酸氨基转移酶(AST)ᵃ  U/L  男 15～45；脚注：ᵃ 试剂中含有5'-磷酸吡哆醛。"
    },
    {
      "id": "wst404_1_2012-4",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 13,
      "high": 40,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) 第1行 AST(带脚注a)",
      "conditions": "脚注a: 试剂中含有5'-磷酸吡哆醛",
      "evidenceQuote": "血清天门冬氨酸氨基转移酶(AST)ᵃ  U/L  女 13～40；脚注：ᵃ 试剂中含有5'-磷酸吡哆醛。"
    }
  ],
  "ALP": [
    {
      "id": "wst404_1_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 男性未再按年龄分组)"
      },
      "low": 45,
      "high": 125,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) ALP 行",
      "conditions": "标准未对 ALP 标注试剂条件",
      "evidenceQuote": "血清碱性磷酸酶(ALP)  U/L  男 45～125"
    },
    {
      "id": "wst404_1_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 49
        }
      },
      "low": 35,
      "high": 100,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) ALP 行",
      "conditions": "标准未对 ALP 标注试剂条件",
      "evidenceQuote": "血清碱性磷酸酶(ALP)  U/L  女(20～49岁) 35～100"
    },
    {
      "id": "wst404_1_2012-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 50,
          "max": 79
        }
      },
      "low": 50,
      "high": 135,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) ALP 行",
      "conditions": "标准未对 ALP 标注试剂条件",
      "evidenceQuote": "血清碱性磷酸酶(ALP)  U/L  女(50～79岁) 50～135"
    }
  ],
  "GGT": [
    {
      "id": "wst404_1_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 10,
      "high": 60,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) GGT 行",
      "conditions": "标准未对 GGT 标注试剂条件",
      "evidenceQuote": "血清γ-谷氨酰基转移酶(GGT)  U/L  男 10～60"
    },
    {
      "id": "wst404_1_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "note": "成年人 (中国成年人群; 该行未单列年龄)"
      },
      "low": 7,
      "high": 45,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_1_2012",
      "locator": "表1(续) GGT 行",
      "conditions": "标准未对 GGT 标注试剂条件",
      "evidenceQuote": "血清γ-谷氨酰基转移酶(GGT)  U/L  女 7～45"
    }
  ],
  "TP": [
    {
      "id": "wst404_2_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (中国成年人群; 表1未单列年龄)"
      },
      "low": 65,
      "high": 85,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst404_2_2012",
      "locator": "4.1 表1",
      "conditions": "标准正文表1未注明方法条件",
      "evidenceQuote": "血清总蛋白(TP)  g/L  男/女 65～85"
    }
  ],
  "ALB": [
    {
      "id": "wst404_2_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (中国成年人群; 表1未单列年龄)"
      },
      "low": 40,
      "high": 55,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst404_2_2012",
      "locator": "4.1 表1",
      "conditions": "标准正文表1未注明方法条件",
      "evidenceQuote": "血清白蛋白(ALB)  g/L  男/女 40～55"
    }
  ],
  "GLB": [
    {
      "id": "wst404_2_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (中国成年人群; 表1未单列年龄)"
      },
      "low": 20,
      "high": 40,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst404_2_2012",
      "locator": "4.1 表1",
      "conditions": "标准正文表1未注明方法条件",
      "evidenceQuote": "血清球蛋白(GLB)  g/L  男/女 20～40"
    }
  ],
  "AG_RATIO": [
    {
      "id": "wst404_2_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (中国成年人群; 表1未单列年龄)"
      },
      "low": 1.2,
      "high": 2.4,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "",
      "sourceId": "src_wst404_2_2012",
      "locator": "4.1 表1",
      "conditions": "标准正文表1未注明方法条件；单位栏为空",
      "evidenceQuote": "白蛋白/球蛋白比值(A/G)  男/女 (1.2～2.4)：1"
    }
  ],
  "TBIL": [
    {
      "id": "wst404_4_2018-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "high": 26,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_4_2018",
      "locator": "4.1 表1",
      "conditions": "方法: 重氮法/钒酸盐氧化法, 计量学溯源至 NIST SRM 916a (附录B 表B.1)",
      "evidenceQuote": "4.1 中国成年人群（20岁～79岁）血清总胆红素、直接胆红素参考区间见表1。 表1 …… 项目 分组 参考范围 (μmol/L) 血清总胆红素(TBIL) 男 ≤26.0"
    },
    {
      "id": "wst404_4_2018-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "high": 21,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_4_2018",
      "locator": "4.1 表1",
      "conditions": "同上",
      "evidenceQuote": "血清总胆红素(TBIL) …… 女 ≤21.0"
    },
    {
      "id": "wst404_4_2018-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "high": 23,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_4_2018",
      "locator": "4.1 表1",
      "conditions": "男/女合并行，性别未区分时使用",
      "evidenceQuote": "血清总胆红素(TBIL) …… 男/女 ≤23.0"
    }
  ],
  "DBIL": [
    {
      "id": "wst404_4_2018-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "high": 8,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_4_2018",
      "locator": "4.1 表1、注2",
      "conditions": "系统a: 罗氏配套系统(重氮法)。直接胆红素无国际公认的计量学溯源标准，因此该区间是系统特异的。",
      "evidenceQuote": "血清直接胆红素(DBIL) 系统a ≤8.0；注1：直接胆红素无国际公认的计量学溯源标准，因此本文件目前提供系统特异的参考区间。注2：系统a：罗氏配套系统；系统b：贝克曼DXC系列配套系统；系统c：贝克曼AU系列配套系统，均为重氮法。"
    },
    {
      "id": "wst404_4_2018-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "high": 4,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_4_2018",
      "locator": "4.1 表1、注2",
      "conditions": "系统b: 贝克曼 DXC 系列配套系统; 系统c: 贝克曼 AU 系列配套系统(均为重氮法)",
      "evidenceQuote": "血清直接胆红素(DBIL) 系统b、c ≤4.0"
    }
  ],
  "K": [
    {
      "id": "wst404_3_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (成年人群; 年龄范围在所见扫描页未印出)"
      },
      "low": 3.5,
      "high": 5.3,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_3_2012",
      "locator": "表1",
      "conditions": "Method not visible in the scanned pages. Only a secondary site (antpedia) lists indirect ISE, so this is unconfirmed.",
      "evidenceQuote": "血清钾(K) mmol/L 男/女 3.5～5.3"
    }
  ],
  "NA": [
    {
      "id": "wst404_3_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (成年人群; 年龄范围在所见扫描页未印出)"
      },
      "low": 137,
      "high": 147,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_3_2012",
      "locator": "表1",
      "conditions": "Method not visible in the scanned pages (see K).",
      "evidenceQuote": "血清钠(Na) mmol/L 男/女 137～147"
    }
  ],
  "CL": [
    {
      "id": "wst404_3_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "note": "成年人 (成年人群; 年龄范围在所见扫描页未印出)"
      },
      "low": 99,
      "high": 110,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_3_2012",
      "locator": "表1",
      "conditions": "Method not visible in the scanned pages (see K).",
      "evidenceQuote": "血清氯(Cl) mmol/L 男/女 99～110"
    }
  ],
  "UREA": [
    {
      "id": "wst404_5_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 59
        }
      },
      "low": 3.1,
      "high": 8,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "Urea assay: 酶法 (表B.1), traceable to NIST SRM 909.",
      "evidenceQuote": "血清尿素(Urea) mmol/L 男(20~59岁) 3.1~8.0"
    },
    {
      "id": "wst404_5_2015-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 60,
          "max": 79
        }
      },
      "low": 3.6,
      "high": 9.5,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "酶法",
      "evidenceQuote": "男(60~79岁) 3.6~9.5"
    },
    {
      "id": "wst404_5_2015-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 59
        }
      },
      "low": 2.6,
      "high": 7.5,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "酶法",
      "evidenceQuote": "女(20~59岁) 2.6~7.5"
    },
    {
      "id": "wst404_5_2015-4",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 60,
          "max": 79
        }
      },
      "low": 3.1,
      "high": 8.8,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "酶法",
      "evidenceQuote": "女(60~79岁) 3.1~8.8"
    }
  ],
  "CREA": [
    {
      "id": "wst404_5_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 59
        }
      },
      "low": 57,
      "high": 97,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "Enzymatic or picric-acid method, only if the lab's creatinine result is traceable to ID-MS (5.1.1, 表B.1).",
      "evidenceQuote": "血清肌酐(Crea) μmol/L 男(20~59岁) 57~97"
    },
    {
      "id": "wst404_5_2015-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 60,
          "max": 79
        }
      },
      "low": 57,
      "high": 111,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "Same as above.",
      "evidenceQuote": "男(60~79岁) 57~111"
    },
    {
      "id": "wst404_5_2015-3",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 59
        }
      },
      "low": 41,
      "high": 73,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "Same as above.",
      "evidenceQuote": "女(20~59岁) 41~73"
    },
    {
      "id": "wst404_5_2015-4",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 60,
          "max": 79
        }
      },
      "low": 41,
      "high": 81,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "μmol/L",
      "sourceId": "src_wst404_5_2015",
      "locator": "表1",
      "conditions": "Same as above.",
      "evidenceQuote": "女(60~79岁) 41~81"
    }
  ],
  "CA": [
    {
      "id": "wst404_6_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 2.11,
      "high": 2.52,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_6_2015",
      "locator": "表1",
      "conditions": "Methods in 表B.1: 邻甲酚酞络合酮比色法 / 间接离子选择电极法换算, traceable to NIST SRM 956c. Serum specimens.",
      "evidenceQuote": "血清总钙(Ca) mmol/L 男/女 2.11~2.52"
    }
  ],
  "MG": [
    {
      "id": "wst404_6_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.75,
      "high": 1.02,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_6_2015",
      "locator": "表1",
      "conditions": "Methods in 表B.1: 二甲苯胺蓝法 / calmagite比色法, traceable to atomic absorption spectrometry.",
      "evidenceQuote": "血清镁(Mg) mmol/L 男/女 0.75~1.02"
    }
  ],
  "P": [
    {
      "id": "wst404_6_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.85,
      "high": 1.51,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mmol/L",
      "sourceId": "src_wst404_6_2015",
      "locator": "表1",
      "conditions": "Method in 表B.1: 磷钼酸紫外法 (no metrological traceability stated). A.4.1 says no serum-matrix certified reference material exists for inorganic phosphorus.",
      "evidenceQuote": "血清无机磷(IP) mmol/L 男/女 0.85~1.51"
    }
  ],
  "WBC": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 3.5,
      "high": 9.5,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法; 附录A: 肘前静脉采血, EDTA 抗凝",
      "evidenceQuote": "白细胞计数(WBC) ×10⁹/L 男/女 3.5～9.5"
    }
  ],
  "NEUT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 1.8,
      "high": 6.3,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "中性粒细胞绝对值(Neut#) ×10⁹/L 男/女 1.8～6.3"
    }
  ],
  "NEUT_PCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 40,
      "high": 75,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "中性粒细胞百分数(Neut%) % 男/女 40～75"
    }
  ],
  "LYMPH": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 1.1,
      "high": 3.2,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "淋巴细胞绝对值(Lymph#) ×10⁹/L 男/女 1.1～3.2"
    }
  ],
  "LYMPH_PCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 20,
      "high": 50,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "淋巴细胞百分数(Lymph%) % 男/女 20～50"
    }
  ],
  "MONO": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.1,
      "high": 0.6,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "单核细胞绝对值(Mono#) ×10⁹/L 男/女 0.1～0.6"
    }
  ],
  "MONO_PCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 3,
      "high": 10,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "单核细胞百分数(Mono%) % 男/女 3～10"
    }
  ],
  "EO": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.02,
      "high": 0.52,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "嗜酸性粒细胞绝对值(Eos#) ×10⁹/L 男/女 0.02～0.52"
    }
  ],
  "EO_PCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.4,
      "high": 8,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "嗜酸性粒细胞百分数(Eos%) % 男/女 0.4～8.0"
    }
  ],
  "BASO": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0,
      "high": 0.06,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "嗜碱性粒细胞绝对值(Baso#) ×10⁹/L 男/女 0～0.06"
    }
  ],
  "BASO_PCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0,
      "high": 1,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "嗜碱性粒细胞百分数(Baso%) % 男/女 0～1"
    }
  ],
  "RBC": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 4.3,
      "high": 5.8,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^12/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "红细胞计数(RBC) ×10¹²/L 男 4.3～5.8"
    },
    {
      "id": "wst405_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 3.8,
      "high": 5.1,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^12/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "红细胞计数(RBC) ×10¹²/L 女 3.8～5.1"
    }
  ],
  "HGB": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 130,
      "high": 175,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "血红蛋白(Hb) g/L 男 130～175"
    },
    {
      "id": "wst405_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 115,
      "high": 150,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "血红蛋白(Hb) g/L 女 115～150"
    }
  ],
  "HCT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.4,
      "high": 0.5,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "L/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "红细胞比容(Hct) L/L 男 0.40～0.50"
    },
    {
      "id": "wst405_2012-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 0.35,
      "high": 0.45,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "L/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "红细胞比容(Hct) L/L 女 0.35～0.45"
    }
  ],
  "MCV": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 82,
      "high": 100,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "fL",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "平均红细胞容积(MCV) fL 男/女 82～100"
    }
  ],
  "MCH": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 27,
      "high": 34,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "pg",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "平均红细胞血红蛋白量(MCH) pg 男/女 27～34"
    }
  ],
  "MCHC": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 316,
      "high": 354,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "平均红细胞血红蛋白浓度(MCHC) g/L 男/女 316～354"
    }
  ],
  "PLT": [
    {
      "id": "wst405_2012-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 125,
      "high": 350,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "10^9/L",
      "sourceId": "src_wst405_2012",
      "locator": "表1(续)",
      "conditions": "静脉血, 仪器检测方法",
      "evidenceQuote": "血小板计数(PLT) ×10⁹/L 男/女 125～350"
    }
  ],
  "ECHO_AO": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 23.8,
      "high": 36.4,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表5 Ao-s 男性总数(n＝678), 95%参考值范围",
      "evidenceQuote": "Ao-s(mm): 23.8-36.4"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 21.3,
      "high": 33.5,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表5 Ao-s 女性总数(n＝716), 95%参考值范围",
      "evidenceQuote": "Ao-s (主动脉窦部内径) | 23.8-36.4 | 21.3-33.5"
    }
  ],
  "ECHO_LA": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 23.5,
      "high": 38.7,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表2 LA-ap 男性总数(n＝678)",
      "evidenceQuote": "LA-ap(mm) | 男性: 23.5-38.7"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 22,
      "high": 36.8,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表2 LA-ap 女性总数",
      "evidenceQuote": "男性总数: 23.5-38.7 mm | 女性总数: 22.0-36.8 mm"
    }
  ],
  "ECHO_LVDD": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 38.4,
      "high": 54,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVEDD 男性总数",
      "evidenceQuote": "LVEDD(mm): 38.4-54.0"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 36.7,
      "high": 49.7,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVEDD 女性总数",
      "evidenceQuote": "LVEDD(mm) | 男性: 38.4-54.0 | 女性: 36.7-49.7"
    }
  ],
  "ECHO_LVDS": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 22.6,
      "high": 38.6,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVESD 男性总数",
      "evidenceQuote": "LVESD(mm): 22.6-38.6"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 20.8,
      "high": 35.4,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVESD 女性总数",
      "evidenceQuote": "LVESD(mm) | 男性: 22.6-38.6 | 女性: 20.8-35.4"
    }
  ],
  "ECHO_IVS": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 6.4,
      "high": 11.4,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 IVSd 男性总数",
      "evidenceQuote": "IVSd(mm): 6.4-11.4"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 5.6,
      "high": 10.6,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 IVSd 女性总数",
      "evidenceQuote": "IVSd(mm) | 男性: 6.4-11.4 | 女性: 5.6-10.6"
    }
  ],
  "ECHO_LVPW": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 6.3,
      "high": 11.1,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVPWd 男性总数",
      "evidenceQuote": "LVPWd(mm): 6.3-11.1"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 5.5,
      "high": 10.3,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "mm",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVPWd 女性总数",
      "evidenceQuote": "LVPWd(mm) | 男性: 6.3-11.1 | 女性: 5.5-10.3"
    }
  ],
  "ECHO_LVEF": [
    {
      "id": "cn_echo_2016-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "male",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 52.6,
      "high": 76.2,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVEF 男性总数",
      "evidenceQuote": "LVEF(%): 52.6-76.2"
    },
    {
      "id": "cn_echo_2016-2",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "sex": "female",
        "age": {
          "min": 18,
          "max": 79
        }
      },
      "low": 52.8,
      "high": 77.2,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "%",
      "sourceId": "src_cn_echo_2016",
      "locator": "表3 LVEF 女性总数",
      "evidenceQuote": "LVEF(%) | 男性: 52.6-76.2 | 女性: 52.8-77.2"
    }
  ],
  "CK": [
    {
      "id": "wst404_7_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "male",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 50,
      "high": 310,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_7_2015",
      "locator": "4.1; 表1",
      "evidenceQuote": "血清肌酸激酶(CK) U/L / 男 50~310"
    },
    {
      "id": "wst404_7_2015-2",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "sex": "female",
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 40,
      "high": 200,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_7_2015",
      "locator": "4.1; 表1",
      "evidenceQuote": "血清肌酸激酶(CK) U/L / 女 40~200"
    }
  ],
  "AMY": [
    {
      "id": "wst404_8_2015-1",
      "kind": "reference",
      "level": "national_cn",
      "population": {
        "age": {
          "min": 20,
          "max": 79
        }
      },
      "low": 35,
      "high": 135,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "U/L",
      "sourceId": "src_wst404_8_2015",
      "locator": "4.1; 表1",
      "evidenceQuote": "血清淀粉酶(AMY) U/L 男/女 35~135"
    }
  ],
  "APOA1": [
    {
      "id": "cn_lipid_guideline_2023-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "note": "成年人"
      },
      "low": 1.2,
      "high": 1.6,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_cn_lipid_guideline_2023",
      "locator": "§3.6 载脂蛋白A1，p.241",
      "conditions": "指南对“正常人群”的描述性范围，不是判定切点，也不是国家标准参考区间。",
      "evidenceQuote": "正常人群ApoA1水平多在1.20~1.60 g/L范围内，女性略高于男性。"
    }
  ],
  "APOB": [
    {
      "id": "cn_lipid_guideline_2023-1",
      "kind": "reference",
      "level": "cn_guideline",
      "population": {
        "note": "成年人"
      },
      "low": 0.8,
      "high": 1.1,
      "lowInclusive": true,
      "highInclusive": true,
      "unit": "g/L",
      "sourceId": "src_cn_lipid_guideline_2023",
      "locator": "§3.7 载脂蛋白B，p.242",
      "conditions": "描述性范围，不是判定切点。",
      "evidenceQuote": "正常人群中血清 ApoB 在 0.80~1.10 g/L 范围内。"
    }
  ]
};

export const VERIFIED_THRESHOLDS: ThresholdInput[] = [
  {
    "id": "bmi_cn",
    "indicatorCodes": [
      "BMI"
    ],
    "name_zh": "成人体重分类（体质指数）",
    "kind": "category",
    "unit": "kg/m²",
    "population": {
      "age": {
        "min": 18
      }
    },
    "categories": [
      {
        "label_zh": "体重过低",
        "high": 18.5,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "体重正常",
        "low": 18.5,
        "high": 24,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "超重",
        "low": 24,
        "high": 28,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "肥胖",
        "low": 28,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_nhc_weight_mgmt_2024",
    "locator": "一、体重的分类标准；附表1（引自 WS/T 428—2013 表1）",
    "level": "national_cn",
    "evidenceQuote": "根据中国 18 岁及以上成人 BMI 评判标准（见附表 1），我国健康成年人的 BMI 正常范围为 18.5kg/m2≤BMI<24.0kg/m2，BMI<18.5kg/m2 为体重过低，24.0kg/m2≤BMI<28.0kg/m2 为超重，BMI≥28.0kg/m2 为肥胖。｜附表1：体重过低 <18.5｜体重正常 18.5～23.9｜超重 24.0～27.9｜肥胖 ≥28.0｜引自：《成人体重判定》（WS/T 428—2013）"
  },
  {
    "id": "bmi_obesity_grade_cn",
    "indicatorCodes": [
      "BMI"
    ],
    "name_zh": "肥胖症程度分级（体质指数）",
    "kind": "category",
    "unit": "kg/m²",
    "population": {
      "note": "成年人"
    },
    "categories": [
      {
        "label_zh": "低体重状态",
        "high": 18.5,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "正常体重",
        "low": 18.5,
        "high": 24,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "超重",
        "low": 24,
        "high": 28,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "轻度肥胖症",
        "low": 28,
        "high": 32.5,
        "inclusivity": "[)",
        "severity": "moderate"
      },
      {
        "label_zh": "中度肥胖症",
        "low": 32.5,
        "high": 37.5,
        "inclusivity": "[)",
        "severity": "severe"
      },
      {
        "label_zh": "重度肥胖症",
        "low": 37.5,
        "high": 50,
        "inclusivity": "[)",
        "severity": "severe"
      },
      {
        "label_zh": "极重度肥胖症",
        "low": 50,
        "inclusivity": "[)",
        "severity": "severe"
      }
    ],
    "sourceId": "src_nhc_obesity_2024",
    "locator": "四（二）1.基于体质指数的诊断标准",
    "level": "national_cn",
    "evidenceQuote": "在我国成年人群中，BMI 低于 18.5 kg/m2 为低体重状态，达到 18.5kg/m2 且低于 24kg/m2 为正常体重，达到 24kg/m2 且低于 28kg/m2 为超重，达到或超过 28kg/m2 为肥胖症[30]。为指导临床诊疗，需要对肥胖症的程度进一步分级，根据肥胖症国际分级标准及亚洲人群特征，以及本指南专家组的讨论共识，建议 BMI 达到 28.0kg/m2 且低于 32.5kg/m2为轻度肥胖症、达到 32.5kg/m2 且低于 37.5 kg/m2 为中度肥胖症、达到 37.5kg/m2 且低于 50 kg/m2 为重度肥胖症、达到或超过 50 kg/m2 为极重度肥胖症[31, 32]。"
  },
  {
    "id": "waist_cn_male",
    "indicatorCodes": [
      "WAIST"
    ],
    "name_zh": "成人中心型肥胖分类（腰围，男性）",
    "kind": "category",
    "unit": "cm",
    "population": {
      "sex": "male",
      "age": {
        "min": 18
      }
    },
    "categories": [
      {
        "label_zh": "正常腰围",
        "high": 85,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "中心型肥胖前期",
        "low": 85,
        "high": 90,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "中心型肥胖",
        "low": 90,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_nhc_weight_mgmt_2024",
    "locator": "附表2 根据腰围对成人中心型肥胖分类（引自 WS/T 428—2013 表2）",
    "level": "national_cn",
    "evidenceQuote": "根据腰围对成人中心型肥胖分类｜…｜中心型肥胖前期 85cm≤腰围<90cm 80cm≤腰围<85cm｜中心型肥胖 腰围≥90cm 腰围≥85cm｜引自：《成人体重判定》（WS/T 428—2013）"
  },
  {
    "id": "waist_cn_female",
    "indicatorCodes": [
      "WAIST"
    ],
    "name_zh": "成人中心型肥胖分类（腰围，女性）",
    "kind": "category",
    "unit": "cm",
    "population": {
      "sex": "female",
      "age": {
        "min": 18
      }
    },
    "categories": [
      {
        "label_zh": "正常腰围",
        "high": 80,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "中心型肥胖前期",
        "low": 80,
        "high": 85,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "中心型肥胖",
        "low": 85,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_nhc_weight_mgmt_2024",
    "locator": "附表2 根据腰围对成人中心型肥胖分类（引自 WS/T 428—2013 表2）",
    "level": "national_cn",
    "evidenceQuote": "根据腰围对成人中心型肥胖分类｜…｜中心型肥胖前期 85cm≤腰围<90cm 80cm≤腰围<85cm｜中心型肥胖 腰围≥90cm 腰围≥85cm｜引自：《成人体重判定》（WS/T 428—2013）"
  },
  {
    "id": "whr_cn_male",
    "indicatorCodes": [
      "WHR"
    ],
    "name_zh": "腰臀比（中心性肥胖，男性）",
    "kind": "category",
    "unit": "",
    "population": {
      "sex": "male",
      "note": "成年人"
    },
    "categories": [
      {
        "label_zh": "未达中心性肥胖（腰臀比）",
        "high": 0.9,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "中心性肥胖",
        "low": 0.9,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_nhc_obesity_2024",
    "locator": "四（二）2.基于体型特征的诊断标准",
    "level": "national_cn",
    "evidenceQuote": "此外，腰围/臀围比（waist-hip ratio, WHR）是另一个反映中心性肥胖的指标，当 WHR≥0.90（男性）和≥0.85（女性）时，也可诊断为中心性肥胖[36]。"
  },
  {
    "id": "whr_cn_female",
    "indicatorCodes": [
      "WHR"
    ],
    "name_zh": "腰臀比（中心性肥胖，女性）",
    "kind": "category",
    "unit": "",
    "population": {
      "sex": "female",
      "note": "成年人"
    },
    "categories": [
      {
        "label_zh": "未达中心性肥胖（腰臀比）",
        "high": 0.85,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "中心性肥胖",
        "low": 0.85,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_nhc_obesity_2024",
    "locator": "四（二）2.基于体型特征的诊断标准",
    "level": "national_cn",
    "evidenceQuote": "此外，腰围/臀围比（waist-hip ratio, WHR）是另一个反映中心性肥胖的指标，当 WHR≥0.90（男性）和≥0.85（女性）时，也可诊断为中心性肥胖[36]。"
  },
  {
    "id": "glu_fpg_cn",
    "indicatorCodes": [
      "GLU"
    ],
    "name_zh": "空腹静脉血浆葡萄糖（糖代谢状态分类/糖尿病诊断）",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "note": "成人（指南未限定年龄）"
    },
    "categories": [
      {
        "label_zh": "正常血糖",
        "high": 6.1,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "空腹血糖受损（IFG）",
        "low": 6.1,
        "high": 7,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "糖尿病（达到诊断切点；无典型症状者需改日复查确认）",
        "low": 7,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cds_dm_2024",
    "locator": "（一）糖尿病诊断标准；表2 糖代谢状态分类（WHO 1999 年）",
    "level": "cn_guideline",
    "evidenceQuote": "表 2 糖代谢状态分类（WHO 1999 年）｜正常血糖｜静脉血浆葡萄糖（mmol/L）｜<6.1｜≥6.1，<7.0｜<7.0｜≥7.0｜……如果有典型的糖尿病症状（如烦渴多饮、多尿、多食、不明原因体重下降），满足空腹静脉血浆葡萄糖≥7.0 mmol/L，或 OGTT 2 h 静脉血浆葡萄 糖 ≥11.1 mmol/L，或 HbA1c≥6.5%，或 随 机 静 脉 血浆葡萄糖≥11.1 mmol/L，可诊断为糖尿病；"
  },
  {
    "id": "glu_2h_cn",
    "indicatorCodes": [
      "GLU_2H"
    ],
    "name_zh": "OGTT 2 h（糖负荷后 2 h）静脉血浆葡萄糖",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "note": "成人（指南未限定年龄）"
    },
    "categories": [
      {
        "label_zh": "正常血糖",
        "high": 7.8,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "糖耐量减低（IGT）",
        "low": 7.8,
        "high": 11.1,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "糖尿病（达到诊断切点；无典型症状者需改日复查确认）",
        "low": 11.1,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cds_dm_2024",
    "locator": "（一）糖尿病诊断标准；表2 糖代谢状态分类（WHO 1999 年）",
    "level": "cn_guideline",
    "evidenceQuote": "表 2 糖代谢状态分类（WHO 1999 年）｜…｜糖负荷后 2 h｜<7.8｜<7.8｜≥7.8，<11.1｜……满足空腹静脉血浆葡萄糖≥7.0 mmol/L，或 OGTT 2 h 静脉血浆葡萄 糖 ≥11.1 mmol/L，或 HbA1c≥6.5%，或 随 机 静 脉 血浆葡萄糖≥11.1 mmol/L，可诊断为糖尿病；"
  },
  {
    "id": "glu_random_cn",
    "indicatorCodes": [
      "GLU"
    ],
    "name_zh": "随机静脉血浆葡萄糖（仅在有典型糖尿病症状时用于诊断）",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "note": "成人（指南未限定年龄）",
      "condition": "有典型糖尿病症状时"
    },
    "categories": [
      {
        "label_zh": "糖尿病（须伴典型糖尿病症状）",
        "low": 11.1,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cds_dm_2024",
    "locator": "（一）糖尿病诊断标准；糖尿病诊断标准表（紧随表2）",
    "level": "cn_guideline",
    "evidenceQuote": "典型糖尿病症状｜加上随机血糖｜或加上空腹血糖｜或加上 OGTT 2 h 血糖｜或加上 HbA1c｜无糖尿病典型症状者，需改日复查确认（不包括随机血糖）｜……如果有典型的糖尿病症状（如烦渴多饮、多尿、多食、不明原因体重下降），满足……或 随 机 静 脉 血浆葡萄糖≥11.1 mmol/L，可诊断为糖尿病；"
  },
  {
    "id": "hba1c_dx_cn",
    "indicatorCodes": [
      "HBA1C"
    ],
    "name_zh": "糖化血红蛋白（糖尿病诊断切点）",
    "kind": "category",
    "unit": "%",
    "population": {
      "note": "成人（指南未限定年龄）"
    },
    "categories": [
      {
        "label_zh": "未达糖尿病诊断切点",
        "high": 6.5,
        "inclusivity": "[)",
        "severity": "normal",
        "note_zh": "原文只给出异常切点，此类为切点以外的范围"
      },
      {
        "label_zh": "达到糖尿病诊断切点（无典型症状者需改日复查确认）",
        "low": 6.5,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cds_dm_2024",
    "locator": "（一）糖尿病诊断标准；糖尿病诊断标准表（紧随表2）",
    "level": "cn_guideline",
    "evidenceQuote": "满足空腹静脉血浆葡萄糖≥7.0 mmol/L，或 OGTT 2 h 静脉血浆葡萄 糖 ≥11.1 mmol/L，或 HbA1c≥6.5%，或 随 机 静 脉 血浆葡萄糖≥11.1 mmol/L，可诊断为糖尿病；｜或加上 HbA1c｜≥6.5%"
  },
  {
    "id": "ua_hua_cn",
    "indicatorCodes": [
      "UA"
    ],
    "name_zh": "高尿酸血症定义（血尿酸）",
    "kind": "category",
    "unit": "μmol/L",
    "population": {
      "note": "成人"
    },
    "categories": [
      {
        "label_zh": "未达高尿酸血症",
        "high": 420,
        "inclusivity": "[]",
        "severity": "normal"
      },
      {
        "label_zh": "高尿酸血症（非同日2次）",
        "low": 420,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cse_hua_2019",
    "locator": "引言（定义）",
    "level": "cn_guideline",
    "evidenceQuote": "高尿酸血症是嘌呤代谢紊乱引起的代谢异常综合征。无论男性还是女性，非同日2次血尿酸水平超过420 μmol/L，称之为高尿酸血症。"
  },
  {
    "id": "ua_hua_cn_cra2023",
    "indicatorCodes": [
      "UA"
    ],
    "name_zh": "高尿酸血症诊断（空腹血尿酸）",
    "kind": "category",
    "unit": "μmol/L",
    "population": {
      "note": "成人"
    },
    "categories": [
      {
        "label_zh": "未达高尿酸血症",
        "high": 420,
        "inclusivity": "[]",
        "severity": "normal"
      },
      {
        "label_zh": "高尿酸血症（正常嘌呤饮食、非同日两次空腹）",
        "low": 420,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cra_gout_2023",
    "locator": "高尿酸血症诊断",
    "level": "cn_guideline",
    "evidenceQuote": "正常嘌呤饮食状态下，非同日两次空腹检测血尿 酸 >420 μmol/L（7 mg/dl）时 ，诊 断 高 尿 酸 血 症 。"
  },
  {
    "id": "ua_target_ahu_cn",
    "indicatorCodes": [
      "UA"
    ],
    "name_zh": "无症状高尿酸血症降尿酸治疗控制目标",
    "kind": "target",
    "unit": "μmol/L",
    "population": {
      "note": "成人（无症状高尿酸血症、已接受降尿酸治疗者）",
      "condition": "无症状高尿酸血症、已在降尿酸治疗"
    },
    "categories": [
      {
        "label_zh": "达标（伴合并症者目标 <360）",
        "high": 360,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "达标（仅适用于无合并症者，目标 <420）",
        "low": 360,
        "high": 420,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "未达标",
        "low": 420,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cse_hua_2019",
    "locator": "问题2（推荐意见，2C）",
    "level": "cn_guideline",
    "evidenceQuote": "建议无症状高尿酸血症患者出现下列情况时起始降尿酸药物治疗：血尿酸水平≥540 μmol/L(2B)或血尿酸水平≥480 μmol/L且有下列合并症之一：高血压、脂代谢异常、糖尿病、肥胖、脑卒中、冠心病、心功能不全、尿酸性肾石病、肾功能损害(≥CKD2期)(2B)。无合并症者，建议血尿酸控制在<420 μmol/L；伴合并症时，建议控制在<360 μmol/L(2C)。"
  },
  {
    "id": "ua_target_gout_cn",
    "indicatorCodes": [
      "UA"
    ],
    "name_zh": "痛风患者降尿酸治疗控制目标",
    "kind": "target",
    "unit": "μmol/L",
    "population": {
      "note": "成人（痛风患者）",
      "condition": "痛风患者"
    },
    "categories": [
      {
        "label_zh": "低于推荐下限（不建议长期 <180）",
        "high": 180,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "达标（合并痛风石等情况时目标 <300）",
        "low": 180,
        "high": 300,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "达标（一般痛风患者目标 <360）",
        "low": 300,
        "high": 360,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "未达标",
        "low": 360,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cse_hua_2019",
    "locator": "问题3（推荐意见，2B）",
    "level": "cn_guideline",
    "evidenceQuote": "痛风患者，建议血尿酸≥480 μmol/L时，开始降尿酸药物治疗(2C)；血尿酸≥420 μmol/L且合并下列任何情况之一时起始降尿酸药物治疗：痛风发作次数≥2次/年、痛风石、慢性痛风性关节炎、肾结石、慢性肾脏疾病、高血压、糖尿病、血脂异常、脑卒中、缺血性心脏病、心力衰竭和发病年龄<40岁(2B)；……建议痛风患者控制血尿酸<360 μmol/L，合并上述情况之一时，控制血尿酸水平<300 μmol/L(2B)；不建议将血尿酸长期控制在<180 μmol/(2B)。"
  },
  {
    "id": "bp_office_cn",
    "indicatorCodes": [
      "SBP",
      "DBP"
    ],
    "name_zh": "基于诊室血压的血压分类和高血压分级",
    "kind": "category",
    "unit": "mmHg",
    "population": {
      "age": {
        "min": 18
      }
    },
    "categories": [
      {
        "label_zh": "正常血压",
        "bounds": {
          "SBP": {
            "high": 120,
            "inclusivity": "[)"
          },
          "DBP": {
            "high": 80,
            "inclusivity": "[)"
          }
        },
        "severity": "normal"
      },
      {
        "label_zh": "正常高值",
        "bounds": {
          "SBP": {
            "low": 120,
            "high": 140,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 80,
            "high": 90,
            "inclusivity": "[)"
          }
        },
        "severity": "mild"
      },
      {
        "label_zh": "1级高血压(轻度)",
        "bounds": {
          "SBP": {
            "low": 140,
            "high": 160,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 90,
            "high": 100,
            "inclusivity": "[)"
          }
        },
        "severity": "moderate"
      },
      {
        "label_zh": "2级高血压(中度)",
        "bounds": {
          "SBP": {
            "low": 160,
            "high": 180,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 100,
            "high": 110,
            "inclusivity": "[)"
          }
        },
        "severity": "severe"
      },
      {
        "label_zh": "3级高血压(重度)",
        "bounds": {
          "SBP": {
            "low": 180,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 110,
            "inclusivity": "[)"
          }
        },
        "severity": "severe"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "4.5.1 按血压水平分类和分级; 表6 (journal p.612, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "以上分类和分级适用于18岁以上任何年龄的成年人。\n表 6 基于诊室血压的血压分类和高血压分级 (mmHg)\n分类 收缩压 舒张压\n正常血压 <120 和 <80\n正常高值 120~139 和/或 80~89\n高血压 ≥140 和/或 ≥90\n1级高血压(轻度) 140~159 和/或 90~99\n2级高血压(中度) 160~179 和/或 100~109\n3级高血压(重度) ≥180 和/或 ≥110\n单纯收缩期高血压 ≥140 和 <90\n单纯舒张期高血压 <140 和 ≥90\n注:当收缩压和舒张压分属于不同级别时,以较高的分级为准。"
  },
  {
    "id": "bp_home_cn",
    "indicatorCodes": [
      "SBP",
      "DBP"
    ],
    "name_zh": "家庭血压高血压诊断标准(连续5~7d规范化测量的平均值)",
    "kind": "category",
    "unit": "mmHg",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "家庭自测血压（连续5~7天规范测量的平均值）"
    },
    "categories": [
      {
        "label_zh": "未达家庭血压诊断界值",
        "bounds": {
          "SBP": {
            "high": 135,
            "inclusivity": "[)"
          },
          "DBP": {
            "high": 85,
            "inclusivity": "[)"
          }
        },
        "severity": "normal"
      },
      {
        "label_zh": "高血压(家庭血压)",
        "bounds": {
          "SBP": {
            "low": 135,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 85,
            "inclusivity": "[)"
          }
        },
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "4.5.1; 表7 (journal p.613, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "表 7 基于诊室血压、家庭血压和动态血压的高血压诊断标准\n血压类型 测量方式 收缩压/舒张压\n(mmHg)\n诊室血压 非同日3次规范化测量诊室血压,\n3次测量的全部血压值\n≥140和/或≥90\n家庭血压 连续5~7d规范化测量家庭血压,\n所有测量血压读数的平均值\n≥135和/或≥85"
  },
  {
    "id": "bp_abpm_24h_cn",
    "indicatorCodes": [
      "SBP",
      "DBP"
    ],
    "name_zh": "动态血压24h平均值高血压诊断标准",
    "kind": "category",
    "unit": "mmHg",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "24小时动态血压平均值"
    },
    "categories": [
      {
        "label_zh": "未达24h动态血压诊断界值",
        "bounds": {
          "SBP": {
            "high": 130,
            "inclusivity": "[)"
          },
          "DBP": {
            "high": 80,
            "inclusivity": "[)"
          }
        },
        "severity": "normal"
      },
      {
        "label_zh": "高血压(24h动态血压)",
        "bounds": {
          "SBP": {
            "low": 130,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 80,
            "inclusivity": "[)"
          }
        },
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "表7 (journal p.613, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "动态血压 24h平均值 ≥130和/或≥80"
  },
  {
    "id": "bp_abpm_day_cn",
    "indicatorCodes": [
      "SBP",
      "DBP"
    ],
    "name_zh": "动态血压白天(或清醒状态)平均值高血压诊断标准",
    "kind": "category",
    "unit": "mmHg",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "动态血压白天平均值"
    },
    "categories": [
      {
        "label_zh": "未达白天动态血压诊断界值",
        "bounds": {
          "SBP": {
            "high": 135,
            "inclusivity": "[)"
          },
          "DBP": {
            "high": 85,
            "inclusivity": "[)"
          }
        },
        "severity": "normal"
      },
      {
        "label_zh": "高血压(白天动态血压)",
        "bounds": {
          "SBP": {
            "low": 135,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 85,
            "inclusivity": "[)"
          }
        },
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "表7 (journal p.613, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "白天(或清醒状态)的平均值 ≥135和/或≥85"
  },
  {
    "id": "bp_abpm_night_cn",
    "indicatorCodes": [
      "SBP",
      "DBP"
    ],
    "name_zh": "动态血压夜晚(或睡眠状态)平均值高血压诊断标准",
    "kind": "category",
    "unit": "mmHg",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "动态血压夜间平均值"
    },
    "categories": [
      {
        "label_zh": "未达夜间动态血压诊断界值",
        "bounds": {
          "SBP": {
            "high": 120,
            "inclusivity": "[)"
          },
          "DBP": {
            "high": 70,
            "inclusivity": "[)"
          }
        },
        "severity": "normal"
      },
      {
        "label_zh": "高血压(夜间动态血压)",
        "bounds": {
          "SBP": {
            "low": 120,
            "inclusivity": "[)"
          },
          "DBP": {
            "low": 70,
            "inclusivity": "[)"
          }
        },
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "表7 (journal p.613, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "夜晚(或睡眠状态)的平均值 ≥120和/或≥70"
  },
  {
    "id": "bapwv_tod_htn2024",
    "indicatorCodes": [
      "BAPWV_L",
      "BAPWV_R"
    ],
    "name_zh": "影响高血压患者心血管预后的靶器官损害: baPWV",
    "kind": "category",
    "unit": "cm/s",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "高血压患者"
    },
    "categories": [
      {
        "label_zh": "未达靶器官损害界值",
        "high": 1800,
        "inclusivity": "()",
        "severity": "normal"
      },
      {
        "label_zh": "靶器官损害(baPWV≥18 m/s)",
        "low": 1800,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "4.5.2; 表9 影响高血压患者心血管预后的重要因素 - 靶器官损害 (journal p.614, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "表 9 影响高血压患者心血管预后的重要因素 ... 靶器官损害 ... ·cfPWV≥10 m/s或baPWV≥18 m/s"
  },
  {
    "id": "bapwv_tod_consensus2025",
    "indicatorCodes": [
      "BAPWV_L",
      "BAPWV_R"
    ],
    "name_zh": "高血压血管损害诊断标准: 动脉硬化(baPWV)",
    "kind": "category",
    "unit": "cm/s",
    "population": {
      "note": "高血压患者",
      "condition": "高血压患者"
    },
    "categories": [
      {
        "label_zh": "未达动脉硬化界值",
        "high": 1800,
        "inclusivity": "(]",
        "severity": "normal"
      },
      {
        "label_zh": "动脉硬化(baPWV>18 m/s)",
        "low": 1800,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_tod_2025",
    "locator": "2.4.2; 表9 高血压血管损害的评估项目、推荐级别与诊断标准 (p.1115)",
    "level": "cn_consensus",
    "evidenceQuote": "脉搏波传导速度\n（PWV）\ncfPWV、baPWV 基本推荐 动脉硬化：cfPWV＞10 m/s、baPWV＞18 m/s"
  },
  {
    "id": "abi_tod_htn2024",
    "indicatorCodes": [
      "ABI_L",
      "ABI_R"
    ],
    "name_zh": "影响高血压患者心血管预后的靶器官损害: ABI",
    "kind": "category",
    "unit": "",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "高血压患者"
    },
    "categories": [
      {
        "label_zh": "靶器官损害(ABI<0.9)",
        "high": 0.9,
        "inclusivity": "()",
        "severity": "mild"
      },
      {
        "label_zh": "未达靶器官损害界值",
        "low": 0.9,
        "inclusivity": "[)",
        "severity": "normal"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "表9 - 靶器官损害 (journal p.614, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "·ABI<0.9"
  },
  {
    "id": "abi_pad_htn2024",
    "indicatorCodes": [
      "ABI_L",
      "ABI_R"
    ],
    "name_zh": "四肢血压测量: 考虑周围血管病的ABI界值",
    "kind": "category",
    "unit": "",
    "population": {
      "age": {
        "min": 18
      }
    },
    "categories": [
      {
        "label_zh": "应考虑周围血管病",
        "high": 0.9,
        "inclusivity": "(]",
        "severity": "mild"
      },
      {
        "label_zh": "未达该界值",
        "low": 0.9,
        "inclusivity": "()",
        "severity": "normal"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "3.6 四肢血压测量",
    "level": "cn_guideline",
    "evidenceQuote": "通常,下肢血压高于上肢血压,当 ABI≤0.9或两侧上肢或两侧下肢之间的血压差别>15 mmHg时,应考虑周围血管病"
  },
  {
    "id": "abi_consensus2025",
    "indicatorCodes": [
      "ABI_L",
      "ABI_R"
    ],
    "name_zh": "高血压血管损害诊断标准: 踝臂指数(ABI)",
    "kind": "category",
    "unit": "",
    "population": {
      "note": "高血压患者",
      "condition": "高血压患者"
    },
    "categories": [
      {
        "label_zh": "考虑存在外周动脉疾病",
        "high": 0.9,
        "inclusivity": "()",
        "severity": "mild"
      },
      {
        "label_zh": "未达异常界值",
        "low": 0.9,
        "high": 1.4,
        "inclusivity": "[]",
        "severity": "normal"
      },
      {
        "label_zh": "ABI过高, 提示动脉钙化(不能排除外周动脉疾病)",
        "low": 1.4,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_tod_2025",
    "locator": "表9 高血压血管损害的评估项目、推荐级别与诊断标准 (p.1115)",
    "level": "cn_consensus",
    "evidenceQuote": "踝臂指数（ABI） 双侧四肢ABI测定 基本推荐 ABI＜0.9考虑存在外周动脉疾病 ABI过高（如＞1.4）则提示动脉钙化，且结果无法排除外周动脉疾病"
  },
  {
    "id": "abi_elderly_2012",
    "indicatorCodes": [
      "ABI_L",
      "ABI_R"
    ],
    "name_zh": "ABI的诊断标准(老年人四肢动脉粥样硬化性疾病)",
    "kind": "category",
    "unit": "",
    "population": {
      "note": "老年人",
      "condition": "老年人（专家建议的适用对象）"
    },
    "categories": [
      {
        "label_zh": "异常",
        "high": 0.9,
        "inclusivity": "(]",
        "severity": "mild"
      },
      {
        "label_zh": "临界",
        "low": 0.9,
        "high": 1,
        "inclusivity": "()",
        "severity": "mild"
      },
      {
        "label_zh": "正常",
        "low": 1,
        "high": 1.4,
        "inclusivity": "[]",
        "severity": "normal"
      },
      {
        "label_zh": "血管严重钙化或弹性减低",
        "low": 1.4,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_elderly_extremity_as_2012",
    "locator": "(一)ABI - 3．ABI的诊断标准",
    "level": "cn_consensus",
    "evidenceQuote": "ABI定义的正常值为1.00～1.40，≤0.90定义为异常，0.91～0.99为临界，>1.40表明血管严重钙化或弹性减低(Ⅰ，B)"
  },
  {
    "id": "hr_resting_risk_htn2024",
    "indicatorCodes": [
      "HR"
    ],
    "name_zh": "影响高血压患者心血管预后的危险因素: 心率增快",
    "kind": "category",
    "unit": "次/分",
    "population": {
      "age": {
        "min": 18
      },
      "condition": "高血压患者"
    },
    "categories": [
      {
        "label_zh": "未达危险因素界值",
        "high": 80,
        "inclusivity": "(]",
        "severity": "normal"
      },
      {
        "label_zh": "心率增快(静息心率>80次/min)",
        "low": 80,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_htn_2024",
    "locator": "表9 - 危险因素 (journal p.614, inferred)",
    "level": "cn_guideline",
    "evidenceQuote": "·心率增快(静息心率>80次/min )"
  },
  {
    "id": "thr_tc_primary_low_risk",
    "indicatorCodes": [
      "TC"
    ],
    "name_zh": "总胆固醇（TC）合适水平和异常切点",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "仅适用于ASCVD一级预防低危人群；数值为干预前空腹12 h测定"
    },
    "categories": [
      {
        "label_zh": "合适水平",
        "high": 5.2,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "边缘升高",
        "low": 5.2,
        "high": 6.2,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "升高",
        "low": 6.2,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3，p.244（原文为表格，下方原文按行压平，列依次为 TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)）",
    "level": "cn_guideline",
    "evidenceQuote": "合适水平＜ 5.2＜ 3.4-＜ 1.7＜ 4.1＜ 300 | 边缘升高 ≥ 5.2 且＜ 6.2≥ 3.4 且＜ 4.1-≥ 1.7 且＜ 2.3≥ 4.1 且＜ 4.9- | 升高≥ 6.2≥ 4.1-≥ 2.3≥ 4.9≥ 300"
  },
  {
    "id": "thr_ldlc_primary_low_risk",
    "indicatorCodes": [
      "LDL_C"
    ],
    "name_zh": "低密度脂蛋白胆固醇（LDL-C）合适水平和异常切点",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "仅适用于ASCVD一级预防低危人群"
    },
    "categories": [
      {
        "label_zh": "理想水平",
        "high": 2.6,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "合适水平",
        "high": 3.4,
        "inclusivity": "[)",
        "severity": "normal",
        "low": 2.6,
        "note_zh": "原文为“合适水平 <3.4”，其中 <2.6 属于“理想水平”"
      },
      {
        "label_zh": "边缘升高",
        "low": 3.4,
        "high": 4.1,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "升高",
        "low": 4.1,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3，p.244（原文为表格，下方原文按行压平，列依次为 TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)）",
    "level": "cn_guideline",
    "evidenceQuote": "理想水平   -＜ 2.6--＜ 3.4- | 合适水平＜ 5.2＜ 3.4-＜ 1.7＜ 4.1＜ 300 | 边缘升高 ≥ 5.2 且＜ 6.2≥ 3.4 且＜ 4.1-≥ 1.7 且＜ 2.3≥ 4.1 且＜ 4.9- | 升高≥ 6.2≥ 4.1-≥ 2.3≥ 4.9≥ 300"
  },
  {
    "id": "thr_hdlc_primary_low_risk",
    "indicatorCodes": [
      "HDL_C"
    ],
    "name_zh": "高密度脂蛋白胆固醇（HDL-C）降低切点",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "表3不分性别；仅适用于ASCVD一级预防低危人群"
    },
    "categories": [
      {
        "label_zh": "未降低（未达“降低”切点）",
        "low": 1,
        "inclusivity": "[)",
        "severity": "normal",
        "note_zh": "原文只给出异常切点，此类为切点以外的范围"
      },
      {
        "label_zh": "降低",
        "high": 1,
        "inclusivity": "[)",
        "severity": "mild"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3，p.244（原文为表格，下方原文按行压平，列依次为 TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)）",
    "level": "cn_guideline",
    "evidenceQuote": "降低--＜ 1.0---"
  },
  {
    "id": "thr_tg_primary_low_risk",
    "indicatorCodes": [
      "TG"
    ],
    "name_zh": "甘油三酯（TG）合适水平和异常切点",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "仅适用于ASCVD一级预防低危人群；空腹12 h"
    },
    "categories": [
      {
        "label_zh": "合适水平",
        "high": 1.7,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "边缘升高",
        "low": 1.7,
        "high": 2.3,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "升高",
        "low": 2.3,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3，p.244（原文为表格，下方原文按行压平，列依次为 TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)）",
    "level": "cn_guideline",
    "evidenceQuote": "合适水平＜ 5.2＜ 3.4-＜ 1.7＜ 4.1＜ 300 | 边缘升高 ≥ 5.2 且＜ 6.2≥ 3.4 且＜ 4.1-≥ 1.7 且＜ 2.3≥ 4.1 且＜ 4.9- | 升高≥ 6.2≥ 4.1-≥ 2.3≥ 4.9≥ 300"
  },
  {
    "id": "thr_nonhdlc_primary_low_risk",
    "indicatorCodes": [
      "NON_HDL_C"
    ],
    "name_zh": "非高密度脂蛋白胆固醇（非HDL-C）合适水平和异常切点",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "仅适用于ASCVD一级预防低危人群"
    },
    "categories": [
      {
        "label_zh": "理想水平",
        "high": 3.4,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "合适水平",
        "high": 4.1,
        "inclusivity": "[)",
        "severity": "normal",
        "low": 3.4,
        "note_zh": "原文为“合适水平 <4.1”，其中 <3.4 属于“理想水平”"
      },
      {
        "label_zh": "边缘升高",
        "low": 4.1,
        "high": 4.9,
        "inclusivity": "[)",
        "severity": "mild"
      },
      {
        "label_zh": "升高",
        "low": 4.9,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3，p.244（原文为表格，下方原文按行压平，列依次为 TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)）",
    "level": "cn_guideline",
    "evidenceQuote": "理想水平   -＜ 2.6--＜ 3.4- | 合适水平＜ 5.2＜ 3.4-＜ 1.7＜ 4.1＜ 300 | 边缘升高 ≥ 5.2 且＜ 6.2≥ 3.4 且＜ 4.1-≥ 1.7 且＜ 2.3≥ 4.1 且＜ 4.9- | 升高≥ 6.2≥ 4.1-≥ 2.3≥ 4.9≥ 300"
  },
  {
    "id": "thr_lpa_cutpoint",
    "indicatorCodes": [
      "LPA"
    ],
    "name_zh": "脂蛋白(a) [Lp(a)] 切点",
    "kind": "category",
    "unit": "mg/L",
    "population": {
      "age": {
        "min": 18
      },
      "note": "表3的Lp(a)列，同样仅针对ASCVD一级预防低危人群"
    },
    "categories": [
      {
        "label_zh": "合适水平",
        "high": 300,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "升高",
        "low": 300,
        "inclusivity": "[)",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表3 p.244；§3.8 脂蛋白(a) p.242",
    "level": "cn_guideline",
    "evidenceQuote": "通常以 300 mg/L 为切点，高于此水平者 ASCVD 风险增加"
  },
  {
    "id": "thr_ldlc_targets_by_risk",
    "indicatorCodes": [
      "LDL_C"
    ],
    "name_zh": "降脂靶点的目标值：LDL-C 目标值（按ASCVD风险等级）",
    "kind": "target",
    "unit": "mmol/L",
    "population": {
      "note": "成年人；按 ASCVD 风险分层。糖尿病合并高危 ASCVD 者的目标见表15，本条不覆盖。",
      "condition": "需由医生评估的 ASCVD 风险等级"
    },
    "categories": [
      {
        "label_zh": "低危：LDL-C <3.4",
        "high": 3.4,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "中、高危：LDL-C <2.6",
        "high": 2.6,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "极高危：LDL-C <1.8，且较基线降低幅度 >50%",
        "high": 1.8,
        "inclusivity": "[)",
        "severity": "normal"
      },
      {
        "label_zh": "超高危：LDL-C <1.4，且较基线降低幅度 >50%",
        "high": 1.4,
        "inclusivity": "[)",
        "severity": "normal"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "表7，p.247",
    "level": "cn_guideline",
    "evidenceQuote": "低危＜ 3.4 mmol/L | 中、高危*＜ 2.6 mmol/L | 极高危＜ 1.8 mmol/L，且较基线降低幅度 ＞ 50% | 超高危＜ 1.4 mmol/L，且较基线降低幅度 ＞ 50%"
  },
  {
    "id": "thr_tg_severe_pancreatitis",
    "indicatorCodes": [
      "TG"
    ],
    "name_zh": "严重高甘油三酯血症（TG >5.6 mmol/L）与胰腺炎风险",
    "kind": "category",
    "unit": "mmol/L",
    "population": {
      "note": "成年人"
    },
    "categories": [
      {
        "label_zh": "严重升高（指南推荐在此水平启动药物以减少胰腺炎风险）",
        "low": 5.6,
        "inclusivity": "()",
        "severity": "moderate"
      }
    ],
    "sourceId": "src_cn_lipid_guideline_2023",
    "locator": "推荐建议 p.249；§8.1.3(2) p.247；§9.4.2 p.255；妊娠 §11.6 p.258",
    "level": "cn_guideline",
    "evidenceQuote": "TG ＞ 5.6 mmol/L 时，可采用贝特类药物、高纯度 ω-3 脂肪酸或烟酸类药物治疗，减少胰腺炎风险"
  }
];

export const RESEARCH_GAPS: Array<{ research: string; what: string; tried: string }> = [
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "WS/T 404.1—2012 与 WS/T 404.2—2012 表1中的成年年龄范围(404.4 明确写 20～79 岁；404.1 仅在 ALP 女性行写了 20～49/50～79 岁)",
    "tried": "只读了 404.1 第2、3页和 404.2 第2页的正文与表；附录A(参考个体年龄范围)未读。因此 ALT/AST/GGT/TP/ALB 的 age 标为 adult，没有写 20-79。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "WS/T 404.1—2012 与 404.2—2012 的国家卫健委 nhc.gov.cn 官方 PDF 直链",
    "tried": "nhc.gov.cn 的 HTML 列表页对我返回 HTTP 412，搜索没有找到 2012 版 PDF 直链。我改用全国标准信息公共服务平台(hbba.sacinfo.org.cn)的官方在线阅读扫描页作为 primary。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "ALT 表1第1、2行哪一行对应哪种试剂条件的直接文字说明",
    "tried": "标准只在带上标 a 的行写了「试剂中含有5'-磷酸吡哆醛」；「无脚注行 = 不含该辅酶」是推断，没有找到原文直接写出。上标 a 出现在 ALT 第2行的位置是目视判断。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "WS/T 404.4—2018 表头单位「μmol/L」中 μ 字符的原样文字",
    "tried": "PDF 文字层丢失了 μ，只提取到「( mol/L)」；单位写作 μmol/L 按 SI 惯例还原，未目视核对图像。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "WS/T 780—2021 儿童临床常用生化检验项目参考区间的发布/实施日期与状态",
    "tried": "仅在 samr 相近标准列表看到标题，未打开该标准页面；与本任务的成人区间无关。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "WS/T 404.10—2022 在 samr 上的现行状态",
    "tried": "NHC PDF 核实了发布和实施日期，但没有取到对应的 samr 状态页。"
  },
  {
    "research": "r1a_wst404_liver_protein_bili.json",
    "what": "std.samr.gov.cn 上 404.9—2018 页面显示 强制性/现行，与 2026 版代替信息并存",
    "tried": "samr 缓存页面未反映 2026 版；以 NHC 2026 版 PDF 前言为准。"
  },
  {
    "research": "r1b_wst404_electrolyte_kidney_mineral.json",
    "what": "UA (尿酸), CO2 (二氧化碳), GLU (葡萄糖), CYSC (胱抑素C) adult reference intervals in any WS/T standard",
    "tried": "The WS/T 404 series has 10 parts, listed in the forewords of 404.9—2026 and 404.10—2022 (ALT/AST/ALP/GGT; TP/ALB; K/Na/Cl; bilirubin; urea/creatinine; Ca/P/Mg/Fe; LDH/CK; amylase; CRP/PA/TRF/β2-MG; thyroid hormones). None covers UA, CO2, GLU or CYSC. Web searches for a separate WS/T on these analytes found nothing; the only related hit was WS/T 780-2021 (children's biochemistry, not adult). Conclusion: no NHC/WS/T adult interval was found for these four. This is an absence of evidence, not a proof that none exists. The 404.5 appendix only lists UA > 475 μmol/L and fasting glucose ≥ 7.0 mmol/L as exclusion criteria for reference individuals, which are not reference intervals."
  },
  {
    "research": "r1b_wst404_electrolyte_kidney_mineral.json",
    "what": "WS/T 404.3: age range (presumably 20-79) and measurement method (ISE)",
    "tried": "The only full-text copy I could open is a 3-page image scan that lacks appendices A.1-A.3 and B. Table 1 says only 成年人群. The N/K/Cl method (间接离子选择电极法, traceable to flame photometry or coulometric titration) appears only on the antpedia metadata page, not in the standard text I read. The NHC and moh.gov.cn pages returned HTTP 412 and other mirrors were unreachable, so I could not get the full official PDF."
  },
  {
    "research": "r1b_wst404_electrolyte_kidney_mineral.json",
    "what": "Direct std.samr.gov.cn status page for WS/T 404.6—2015",
    "tried": "The 404.5 and 404.3 pages were read (both 现行). For 404.6 I only found the official PDF plus its listing in the 404.9—2026 foreword; the search-indexed page I fetched for the 404.6 slot was 404.7 (现行, 2015-04-21 / 2015-10-01)."
  },
  {
    "research": "r1b_wst404_electrolyte_kidney_mineral.json",
    "what": "Whether WS/T 404.3, 404.5 and 404.6 have been or will be revised",
    "tried": "Searched for 代替 WS/T 404.3—2012 and read the 404.9—2026 foreword. WS/T 404.9 was revised in 2026 and WS/T 403 and WS/T 402 were updated to 2024 editions, so revisions of the other parts are plausible. No revision notice for 404.3, 404.5 or 404.6 was found."
  },
  {
    "research": "r1c_wst405_blood_cells.json",
    "what": "WS/T 405 中老年人(如≥60岁或≥65岁)单独的参考区间",
    "tried": "通读扫描件全文(正文、表1、附录A/B): 表1只有成年人一组, 附录A.2.1称年龄范围20岁~79岁, 每十岁年龄段至少120人, 未按年龄分层给出区间。故不提供单独老年区间, 上表 age 记为 20-79 (成年人整体)。"
  },
  {
    "research": "r1c_wst405_blood_cells.json",
    "what": "RDW_CV、RDW_SD、MPV、PDW、PCT_PLT(血小板压积)的国家标准参考区间",
    "tried": "WS/T 405-2012 表1未包含这些项目(仅18项: WBC、5类白细胞绝对值和百分数、RBC、Hb、Hct、MCV、MCH、MCHC、PLT)。samr 及搜索结果中未发现其他给出这些项目区间的现行 WS/T/GB/T 标准, 未验证, 不给数值。"
  },
  {
    "research": "r1c_wst405_blood_cells.json",
    "what": "nhc.gov.cn 官方原始 PDF 及其原文下载",
    "tried": "nhc.gov.cn 页面(201301/d893733b...shtml)返回 HTTP 412, 无法访问; 全文取自第三方镜像扫描件(secondary), 数值为目视读图, 建议在能访问 nhc.gov.cn 或 ndls.org.cn 时复核。"
  },
  {
    "research": "r1c_wst405_blood_cells.json",
    "what": "末梢血(毛细血管血)参考区间",
    "tried": "标准仅注明“此参考区间适用于静脉血的仪器检测方法”, 未给末梢血区间, 不能套用。"
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "Verbatim text of WS/T 428—2013 itself (表1, 表2)",
    "tried": "NHC PDF http://www.nhc.gov.cn/ewebeditor/uploadfile/2013/08/20130808135715967.pdf is an image-only scan (no text layer; read visually only). chinacdc.cn and chinanutri.cn pages returned HTTP 405, nhc.gov.cn HTML page returned 412. Verbatim WS/T 428 cut-points were instead taken from NHC 体重管理指导原则（2024年版） 附表1/2, which quote WS/T 428."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "协和医学杂志 reprint of the obesity guideline: volume/issue/pages (search summary says 2025, 16(1): 90-108)",
    "tried": "Fetched https://xhyxzz.pumch.cn/article/doi/10.12290/xhyxzz.2024-0918 (title and author confirmed, no citation metadata came through); sciengine PDF did not extract."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "中国糖尿病防治指南（2024版）: exact number/title of the diagnostic-criteria table (presumably 表3) and the 表2 row-label lines",
    "tried": "Line-level search of the extracted PDF text; table title line and 表2 row labels (IFG/IGT/糖尿病) were not recoverable because the extractor emits cells as separate lines and the search tool caps hits."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "中国高尿酸血症相关疾病诊疗多学科专家共识（2023年版）full text, pages (461-480) and verbatim HUA definition",
    "tried": "Journal landing page (abstract only), SinoMed record, sohu/medtrib reposts; zgsyz PDF link returned HTML only."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "2024 update of the Chinese hyperuricemia/gout guideline (Int J Rheum Dis 2025;28(7):e70375): whether the 420 μmol/L definition or targets changed",
    "tried": "Only the PubMed abstract (via relay); Wiley returned 403. Abstract mentions chronic gout target 180-300 μmol/L."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "国家卫健委《成人高尿酸血症与痛风食养指南（2024年版）》 (国卫办食品函〔2024〕53号) HUA definition",
    "tried": "NHC PDF exceeded 10 MB fetch limit; Q&A PDF not text-decodable via WebFetch; Guangxi CDC offers only a .rar. Secondary summaries say 非同日2次空腹血尿酸 >420 μmol/L."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "国家卫健委《成人肥胖食养指南（2024年版）》 waist/BMI table",
    "tried": "NHC PDF fetch via research app failed (no files saved)."
  },
  {
    "research": "r2a_cn_thresholds_body_glucose_ua.json",
    "what": "肥胖症诊疗指南（2024年版） 图1 超重和肥胖症诊疗路径 BMI boxes (24～<27.5, 27.5～<32.5, 32.5～<37.5, ≥37.5)",
    "tried": "Only in an image (read visually by a sub-agent); these boxes do not match the text grades and were not recorded."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "baPWV 3-tier categories (<1400 normal, 1400-1799 borderline, >=1800 elevated) in any Chinese guideline or consensus",
    "tried": "Read the full 2024 hypertension guideline, the 2025 target-organ consensus, the 2020 primary-care guideline and the 2012 elderly extremity-AS recommendations; none contains 1400 cm/s. The 1400 cut-off appears only in research articles and search snippets. It is widely attributed to Japanese sources (not checked). Do not attribute it to a Chinese guideline."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "Thresholds in 脉搏波传导速度检测用于早期血管衰老评价的中国专家共识 (中华高血压杂志 2021;29(12):1168-1172)",
    "tried": "Downloaded the PDF, but CJK text was lost in extraction (only fragments like 'cfPWV>10 m/s' in context citing ESH/ESC). The HTML page shows only the introduction. No threshold recorded."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "Thresholds in 同步四肢血压和臂踝脉搏波速度测量临床应用中国专家共识 (中国循环杂志 2020;35(6):521-528)",
    "tried": "The chinacirculation.org PDF is blocked by an Aliyun WAF, WebFetch returned 404, and Wanfang has the abstract only. A 2022 article (临床心血管病杂志 2022;38(4):318) cites it as '有相关组织把 baPWV>18 m/s作为血管功能衰竭的标志' (secondary only). ABI cut-offs in this consensus are not verified."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "2018 edition details (e.g. cfPWV>=12 m/s and whether baPWV/ABI appeared in its TOD table)",
    "tried": "The 2018 edition was not fetched. The cfPWV 12->10 change and the baPWV addition come only from the 2024 text's own statement."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "下肢动脉硬化闭塞症诊治指南 (中华医学会外科学分会血管外科学组; 中华普通外科学文献(电子版) 2016;10(1):1-18) ABI criteria",
    "tried": "The landing page gave metadata only (the PDF link was non-functional). The 'ABI<=0.9' criterion was seen only in a search-engine summary."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "《血管衰老标志物专家共识(2023)》 (中国衰老标志物研究联合体), 《中国血管健康评估系统应用指南》, 《血管功能无创性检测技术临床应用中国专家共识》 baPWV/ABI categories",
    "tried": "Web searches found news items on the 2023 consensus but no threshold text. The other two titles were not located. Nothing recorded."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "ABI <=0.40 severe ischaemia band; post-exercise ABI and TBI bands beyond the 2012 document",
    "tried": "Not found in any document read in full. ABI 0.41-0.90 / <=0.40 appeared only in a search snippet."
  },
  {
    "research": "r2b_cn_thresholds_bp_pwv_abi.json",
    "what": "Exact journal page numbers of 2024 guideline tables",
    "tried": "Inferred from PDF page order (PDF p.1 = journal p.603; footer digits reversed in extraction): 表6 p.612, 表7 p.613, 表8-9 p.614, 表10 p.617. Treat as approximate."
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "baPWV 3-tier bands (<1400 normal / 1400-1799 / >=1800 cm/s) and any Chinese baPWV reference range for healthy adults",
    "tried": "2024 hypertension guideline full text; 2025 target-organ consensus; PWV vascular-aging consensus 2021 (zhgxyzz.xml-journal.net; the cert does not match and the PDF would not extract); MedSci abstract pages"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "血管年龄 (vascular age) in any Chinese guideline",
    "tried": "search of extracted 2024 hypertension guideline and related consensus texts; web search"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Primary text of the QUS paragraph in 原发性骨质疏松症诊疗指南(2022)",
    "tried": "chinagp.net (abstract only; the PDF would not download), haoyishu, dxy (login), qk.sjtu interpretation, xhyxzz interpretation"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Chinese normal ECG limits (PR 120-200 ms, QRS, QTc, axis -30°~+90°, HR 60-100 or 50-100)",
    "tried": "常规心电图检查操作指南(简版) (abstract only), 心电图诊断术语规范化中国专家共识(2019) PDF (text extraction failed), Chin J Cardiol 2024;52(6) PDF (no interval norms)"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "TCD adult normal velocity ranges (经颅多普勒超声操作规范及诊断标准指南, 2008)",
    "tried": "web search; 人卫临床助手 page for the 2016 cerebrovascular ultrasound guideline (stenosis criteria only, table in an image)"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Numeric interpretation rules for EBV VCA-IgA/EA-IgA (titre, S/CO, combined risk-score cut-offs) in a Chinese NPC screening consensus",
    "tried": "2018 EBV lab consensus (repost), 2025 NPC biomarker consensus (secondary summaries; full PDF not accessible)"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Primary-text verification of the 13C-UBT sentence '≥4.0为阳性' in the 2020 UBT consensus",
    "tried": "PDF text via research app (only nearby lines retrievable), jsma.net.cn and shsma.org.cn pages (no content), zhihu (403)"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Adult visual-impairment grading (e.g. GB/T 26341 视力残疾, WS/T standards)",
    "tried": "not fetched (out of time budget); GB/T 11533 defines only the chart and the normal standard"
  },
  {
    "research": "r6_new_items_cn.json",
    "what": "Echo LVEF/dimensions: female age-band rows and verbatim character-level check against the PDF",
    "tried": "PDF (hbusqcc mirror) could not be text-extracted; values taken from the publisher HTML via WebFetch"
  },
  {
    "research": "r7_cn_lipid_guideline_2023.json",
    "what": "中国国家/卫生行业标准（WS/T）中 TC、TG、HDL-C、LDL-C、ApoA1、ApoB 的参考区间",
    "tried": "检索了 WS/T 404 系列（临床常用生化检验项目参考区间）：搜到的第1至9部分是 ALT/AST/ALP/GGT、总蛋白/白蛋白、钾钠氯、胆红素、尿素/肌酐、钙磷镁铁、LDH/CK、淀粉酶、CRP/前白蛋白/转铁蛋白/β2微球蛋白，没有看到血脂项目。只找到 WS/T 463—2015《血清低密度脂蛋白胆固醇检测》（nhc.gov.cn），它是检测方法标准，不是参考区间。我没有逐条核对 WS/T 404 的全部分册和 std.samr.gov.cn 上的完整目录，所以只能说“未发现”，不能断言“不存在”。"
  },
  {
    "research": "r7_cn_lipid_guideline_2023.json",
    "what": "官方（primary）PDF核对及现行状态的官方确认",
    "tried": "csc.cma.org.cn 的官方页面能打开（中华心血管病杂志 2023;51(3):221-255），但未抽取其 PDF 文字与镜像逐字比对。未查询 std.samr.gov.cn / nhc.gov.cn（指南不属于国家标准，不在标准库中）。也没有去中国循环杂志官网取原始PDF。"
  },
  {
    "research": "r7_cn_lipid_guideline_2023.json",
    "what": "表3列位置的图像核对",
    "tried": "表3的各列在文本层中被压平，按“TC、LDL-C、HDL-C、TG、非HDL-C、Lp(a)”的列头顺序还原。还原结果与指南通行数值一致（TC 5.2/6.2，LDL-C 3.4/4.1，TG 1.7/2.3，HDL-C <1.0，非HDL-C 4.1/4.9，Lp(a) 300），但没有渲染页面图像逐格核对。"
  },
  {
    "research": "r7_cn_lipid_guideline_2023.json",
    "what": "各风险等级的非HDL-C 目标数值",
    "tried": "指南只给出换算公式“非 HDL-C 目标水平 =LDL-C ＋ 0.8 mmol/L”，没有逐等级列出数值，thr_nonhdlc_targets_by_risk 中的数值为推算值。"
  },
  {
    "research": "r7_cn_lipid_guideline_2023.json",
    "what": "ApoB / ApoA1 的异常切点",
    "tried": "全文检索未发现 ApoB/ApoA1 的“升高/降低”切点，仅有 §3.6、§3.7 的“正常人群”描述性范围（已列入 items）。表2/表3中也没有 ApoB 数值。"
  }
];
